all:
  children:
    load_balancer:
      hosts: #Replace the hostnames with your actual server addresses.
        lb.example.com
    webservers:
      hosts:
        web1.example.com
        web2.example.com
    dbservers:
      hosts:
        db.example.com